version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketsentinel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  websocket:
    build: ./app
    command: python websocket_server.py
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
